### ISSUE TITLE
a problem with vot  dataset eval!

### ISSUE THREAD

**Issue by kuiran** [visionml/pytracking#192] opened 2020-10-13 14:47 UTC
I try to eval atom on vot dataset,but because the differences between the the pytorch version 0.3 and 0.4, i can't import torch.
a error like 

from torch._C import *
RuntimeError: stoi

i search this problem online and add 

system('env -i /home/kuiran/anaconda3/envs/pytracking/bin/python -c "import torch"');

or

system('unset MKL_NUM_THREADS; /home/kuiran/anaconda3/envs/pytracking/bin/python -c "import torch"')

it works but i need to annotate all codes of "import torch " in pytracking.

could you help me how to fix this problem?

Thank you.

One people to explore tracking is so difficult.

**Comment by kuiran** [comment] 2020-10-13 15:16
I brower the issues in the github/vot-toolkit  the problem for supporting the version 0.4 of pytorch still not fixed, I'm cofused about how your team and the people use this code to eval vot dataset.Thank you.

**Comment by kuiran** [comment] 2020-10-14 11:18
add  setenv('MKL_NUM_THREADS','1')  can fix this problem,but a new problem happened as follow

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/kuiran/github/pytracking/pytracking/run_vot.py", line 19, in run_vot
    tracker.run_vot()
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/tracker.py", line 621, in run_vot
    handle = vot.VOT("polygon")
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 92, in __init__
    options = trax.server.ServerOptions(region_format, trax.image.PATH)
AttributeError: module 'trax.server' has no attribute 'ServerOptions'
Exception ignored in: <function VOT.__del__ at 0x7fb0daca39e0>
Traceback (most recent call last):
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 173, in __del__
    self.quit()
  File "/home/kuiran/github/pytracking/pytracking/../pytracking/evaluation/vot.py", line 165, in quit
    self._trax.quit()
AttributeError: 'VOT' object has no attribute '_trax'

wish someone help me. thank you.

**Comment by goutamgmb** [comment] 2020-11-27 16:33
closing this as the issue is a repetition of #193

**Closed by goutamgmb** 2020-11-27 16:33 UTC
