### ISSUE TITLE
Bug in traing COCO2014

### ISSUE THREAD

**Issue by beyondpzk** [visionml/pytracking#18] opened 2019-04-29 02:47 UTC
I find there is a bug when adding the coco2014 dataset into training set,

that is

 "File "../ltr/data/processing_utils.py", line 35, in sample_target
raise Exception('Too small bounding box.')
 Exception: Too small bounding box."

I have checked the coco dataset and find that the bug is from the image 'train2014/COCO_train2014_000000550395.jpg', and the corresponding anno is 

'{'segmentation': [[9.98, 188.56, 15.52, 188.56, 15.52, 188.56, 11.09, 188.56]], 'area': 0.0, 'iscrowd': 0, 'image_id': 550395, 'bbox': [9.98, 188.56, 5.54, 0.0], 'category_id': 1, 'id': 2206849}'.

Maybe we should check the area for every bbox.

**Comment by wangaixue** [comment] 2019-04-29 11:05
@beyondpzk  i also find it. i delete the if ..... in processing_utils.py,but i don not  if it will be affected.

**Comment by wangaixue** [comment] 2019-05-01 10:31
@beyondpzk Have you solve its problem??

**Comment by goutamgmb** [comment] 2019-05-02 15:42
Hi, thanks for notifying the problem. We have now fixed so that the target is denoted as not visible if the area of the bounding box is <= 0. Such frames will not be used for training. Let us know if the problem persists, or if you get error on other datasets.

**Comment by wangaixue** [comment] 2019-05-03 11:52
@ goutamgmb  thanks for your help,but i try the method, but the problem is contiuing in epoch 8.  
                                                                                                                                                   thanks

**Comment by huangbiubiu** [comment] 2019-05-13 11:46
@goutamgmb I was training on 243a056905eb687f4a662c4271210a60f734ea84, and the exception still exists on epoch 13.

**Comment by martin-danelljan** [comment] 2019-05-19 14:47
It should be fixed now.

**Closed** 2019-05-22 12:05 UTC

**Comment by Jh0712-W** [comment] 2024-11-15 03:10
Hello, I have the same problem and the training crashed at epoch 20. Have you solved it yet?
